include_guard()

message("-- Including settings")
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_OSX_DEPLOYMENT_TARGET 10.10)
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")
